; Basic Phong Shader
[Default]
vert = ./basic.vert
frag = ./basic.frag

; Basic Phong Shader with DepthTest OFF
[SkyBox]
vert = ./basic.vert
frag = ./basic.frag
depth = off

; Simple Texture only shader for use with UI drawing
[Sprite]
vert = ./sprite.vert
frag = ./sprite.frag
depth = off

; Simple solid colour wireframe shader that only draws wireframes
[WireFrame]
vert = ./wireframe.vert
frag = ./wireframe.frag
poly = line
